### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GiitSmile** [KingJA/SwitchButton#1]
在Fragment中使用时，设置了 app:strokeRadius="6dp"如果把该控件放在Fragment A,然后跳转到Fragment B,这时候切换回Fragment A，发现控件的圆角不见了，不知道什么原因

**Comment by KingJA** [comment]
可否提供你的代码，可以发我邮箱

**Comment by GiitSmile** [comment]
不好意思，因为是在做项目所以不能提供源码，我看看晚点能不能给你一个Gif动态图看下

2016-09-26 8:47 GMT+08:00 KingJA <notifications@github.com>:

**Comment by Kyoya1714** [comment]
在onRestoreInstanceState，把前面三个 bundle.getInt改为 bundle.getFloat

**Comment by KingJA** [comment]
@Kyoya1714  确实如此，感谢指正
