### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wilxr** [KingJA/SwitchButton#13]
Hello I have a doubt, in design mode I can see the control without problem, but in execution it does not work.
![screenshot_1](https://user-images.githubusercontent.com/36232748/35918974-331c18ec-0bd9-11e8-8e50-62080ee3dc04.png)

**Comment by KingJA** [comment]
@wilxr Could you show me detail about codes?

**Comment by wilxr** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/tools"
    android:orientation="vertical"
    app:ignore="NamespaceTypo">

    <lib.kingja.switchbutton.SwitchMultiButton
        android:id="@+id/mServ"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:padding="8dp"
        app:strokeRadius="5dp"
        app:strokeWidth="1dp"
        app:selectedTab="0"
        app:selectedColor="@color/button_primary_color"
        app:switchTabs="@array/planets_array"
        app:textSize="20sp" />

    </LinearLayout>

**Comment by KingJA** [comment]
@wilxr Have you add 
```
xmlns:app="http://schemas.android.com/apk/res-auto"
```
in father layout, it does work in my case.
Maybe, you should test on another  device.

**Comment by wilxr** [comment]
Thanks you, that was the problem

**Comment by wilxr** [comment]
Is there a multi-choice property?

**Comment by KingJA** [comment]
@wilxr What do mean of'multi-choice property'?

**Comment by wilxr** [comment]
to be able to select 2 or more options, like checkbox

**Comment by KingJA** [comment]
@wilxr it is unavailable in this library.
