### ISSUE TITLE
Remove unnecessary files and manifest declarations

### ISSUE THREAD

**Issue by sosite** [KingJA/SwitchButton#15]
Library version: `1.1.6`

1. 1st of all - you included `tielanti.ttf` and `DeVinneTxtBT.ttf` into library aar file. So my app is 2 MB larger than it should be!
2. In library manifest you have declared `application` tag which is unnecessary in android library modules. So I have to include `tools:replace="android:allowBackup,android:label"` into my manifest file. 
Library manifest can looks simple like:
```
<manifest package="lib.kingja.switchbutton" />
```

---
Temporary fix until lib will be updated

To your app module `build.gradle` add below lines:
```
android {
    ...
    aaptOptions {
        ignoreAssetsPattern "tielanti.ttf:DeVinneTxtBT.ttf"
    }
}

**Comment by KingJA** [comment]
@sosite thanks for reminding. v1.1.7 has fixed it.

**Comment by sosite** [comment]
Nice, thx :)
But you fix only 1st point. Not the 2nd one about manifest file :/
