### ISSUE TITLE
selectedTab字体颜色

### ISSUE THREAD

**Issue by guiying712** [KingJA/SwitchButton#2]
可以添加个字体颜色的属性以及text，不然的话，要是把selectedColor设为白色，就看不到selectedTab中的字了

**Comment by KingJA** [comment]
@guiying712  抱歉，设计的初衷为了简洁，只用两种颜色,，默认白色为未选中颜色，selectedColor为未选中字体颜色。如果你愿意，可以自己改，也很简单。：D
