### ISSUE TITLE
Typo in comments section 

### ISSUE THREAD

**Issue by ritwikdax** [KingJA/SwitchButton#30]
It should be "draw right path"
https://github.com/KingJA/SwitchButton/blob/c36316ae6e8494031eb1c76588f63455580187b7/libk-switchbutton/src/main/java/lib/kingja/switchbutton/SwitchMultiButton.java#L273

And it should be "draw left path"
https://github.com/KingJA/SwitchButton/blob/c36316ae6e8494031eb1c76588f63455580187b7/libk-switchbutton/src/main/java/lib/kingja/switchbutton/SwitchMultiButton.java#L253

**Comment by KingJA** [comment]
@devritwik Thanks, I will fix it in the next version.
