### ISSUE TITLE
change font

### ISSUE THREAD

**Issue by MansoorJafari** [KingJA/SwitchButton#6]
Hi

how to change font each switch button???

**Comment by KingJA** [comment]
@MansoorJafari do you mean typeface?

**Comment by SirLordPouya** [comment]
hi
is there a way to change font (typeface) of the texts ?

**Comment by KingJA** [comment]
@MansoorJafari 
@SirLordPouya 
Hey, gays, I wanna tell you, it support typeface now, in V1.1.6.
